print ("============")
name = input ("Masukkan nama :\n")
nis = input ("Masukkan NIS :\n")
rombel = input ("Masukkan Rombel :\n")
rayon = input ("Masukkan Rayon :\n")
print ("===============")
print ("Nama : "+name+"\nNIS : "+nis+"\nRombel : "+rombel+"\nRayon : "+rayon)
print ("===============")
